module.exports = {
    characterCards: {
        assainCard: {
            cardName     : 'asssain',
            skill        : 'assassinate',
            interestArch : 'none,',
            order        : '1',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        },
        thiefCard: {
            cardName     : 'thief',
            skill        : 'steal',
            interestArch : 'none,',
            order        : '2',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        },
        Magician: {
            cardName     : 'magician',
            skill        : 'exchangeOrDiscardCard',
            interestArch : 'none,',
            order        : '3',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        },
        kingCard: {
            cardName     : 'king',
            skill        : 'none',
            interestArch : 'royalArch',
            order        : '4',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        },
        bishopCard: {
            cardName     : 'bishop',
            skill        : 'none',
            interestArch : 'reliArch',
            order        : '5',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        },
        merchantCard: {
            cardName     : 'merchant',
            skill        : 'twoCoinAuto',
            interestAtch : 'merchArch',
            order        : '6',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        },
        architectCard: {
            cardName     : 'architect',
            skill        : 'twoCardsAuto',
            interestArch : 'none',
            order        : '7',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        },
        warlordCard: {
            cardName     : 'warlord',
            skill        : 'destroy',
            interestArch : 'miliArch',
            order        : '8',
            abandoned    : false,
            selected     : false,
            playerId     : 'none',
            status       : [],
        }
    },

    architectureCards: {
        testCard1 : {
            name: 'testCard1',
            property: 'army',
            addon: 'none',
        },
        testCard2 : {
            name: 'testCard2',
            property: 'royal',
            addon: 'none',
        }
    }
}